package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
	"fmt"
	"log/slog"
	"strings"
	"time"

	"yrdy-kbd/apps/bff/internal/auth"
	"yrdy-kbd/apps/bff/internal/graph/model"
	"yrdy-kbd/apps/bff/internal/kvs"
	"yrdy-kbd/apps/bff/internal/live"
)

// CreateLive is the resolver for the createLive field.
func (r *mutationResolver) CreateLive(ctx context.Context, input model.CreateLiveInput) (*model.Live, error) {
	user, err := auth.FromContext(ctx)
	if err != nil {
		return nil, err
	}

	title := strings.TrimSpace(input.Title)
	if title == "" {
		return nil, fmt.Errorf("title is required")
	}
	if len([]rune(title)) > 120 {
		return nil, fmt.Errorf("title must be 120 characters or less")
	}

	digest, err := live.NewPassphraseDigest(deref(input.Passphrase))
	if err != nil {
		return nil, err
	}

	liveID, err := live.NewID()
	if err != nil {
		return nil, err
	}

	channelName := live.ChannelName(liveID)
	channelARN, err := r.KVS.EnsureSignalingChannel(ctx, channelName)
	if err != nil {
		slog.Error("ensure signaling channel", "error", err)
		return nil, fmt.Errorf("prepare KVS signaling channel")
	}

	var streamARN string
	if input.Record {
		streamARN, err = r.KVS.EnsureStream(ctx, live.StreamName(liveID))
		if err != nil {
			slog.Error("ensure stream", "error", err)
			return nil, fmt.Errorf("prepare KVS stream for recording")
		}
		if err := r.KVS.ConfigureMediaStorage(ctx, channelARN, streamARN); err != nil {
			slog.Error("configure media storage", "error", err)
			return nil, fmt.Errorf("enable KVS media storage")
		}
	}

	entry := live.Live{
		ID:          liveID,
		OwnerID:     user.ID,
		OwnerName:   user.Name,
		Title:       title,
		Public:      input.Public,
		Record:      input.Record,
		Status:      live.StatusCreated,
		ChannelName: channelName,
		ChannelARN:  channelARN,
		StreamARN:   streamARN,
		CreatedAt:   time.Now().UTC(),
		Passphrase:  digest,
	}
	if err := r.LiveStore.Put(entry); err != nil {
		slog.Error("persist live", "liveID", entry.ID, "error", err)
		return nil, fmt.Errorf("persist live")
	}
	slog.Info("live created",
		"event_name", "live_created",
		"live_id", entry.ID,
		"recording_enabled", entry.Record,
		"visibility", map[bool]string{true: "public", false: "private"}[entry.Public],
	)

	return r.toLive(entry, user.ID), nil
}

// StopLive is the resolver for the stopLive field.
func (r *mutationResolver) StopLive(ctx context.Context, liveID string) (*model.Live, error) {
	user, err := auth.FromContext(ctx)
	if err != nil {
		return nil, err
	}
	entry, err := r.requireLive(liveID)
	if err != nil {
		return nil, err
	}
	if entry.OwnerID != user.ID {
		return nil, fmt.Errorf("only the owner can stop this live")
	}

	entry, err = r.LiveStore.Update(entry.ID, func(l *live.Live) {
		if l.Status != live.StatusLive {
			return
		}
		l.Status = live.StatusEnded
		now := time.Now().UTC()
		l.EndedAt = &now
	})
	if err != nil {
		slog.Error("mark live ended", "liveID", liveID, "error", err)
		return nil, fmt.Errorf("update live state")
	}
	slog.Info("broadcast stopped", "event_name", "broadcast_stopped", "live_id", entry.ID)
	return r.toLive(entry, user.ID), nil
}

// CreatePublisherSession is the resolver for the createPublisherSession field.
func (r *mutationResolver) CreatePublisherSession(ctx context.Context, liveID string) (*model.SessionConfig, error) {
	user, err := auth.FromContext(ctx)
	if err != nil {
		return nil, err
	}
	entry, err := r.requireLive(liveID)
	if err != nil {
		return nil, err
	}
	if entry.OwnerID != user.ID {
		return nil, fmt.Errorf("only the owner can broadcast this live")
	}
	if entry.Status == live.StatusEnded {
		return nil, fmt.Errorf("ended lives cannot be restarted")
	}

	session, err := r.KVS.SessionConfig(ctx, kvs.SessionInput{
		ChannelARN: entry.ChannelARN,
		Role:       kvs.RoleMaster,
	})
	if err != nil {
		slog.Error("create publisher session", "liveID", entry.ID, "error", err)
		return nil, fmt.Errorf("create KVS publisher session")
	}

	if _, err := r.LiveStore.Update(entry.ID, func(l *live.Live) {
		l.Status = live.StatusLive
		if l.StartedAt == nil {
			now := time.Now().UTC()
			l.StartedAt = &now
		}
		l.EndedAt = nil
	}); err != nil {
		slog.Error("mark live started", "liveID", entry.ID, "error", err)
		return nil, fmt.Errorf("update live state")
	}
	slog.Info("publisher session created",
		"event_name", "broadcast_started",
		"live_id", entry.ID,
		"recording_enabled", entry.Record,
	)

	return toSessionConfig(entry.ID, session), nil
}

// CreateViewerSession is the resolver for the createViewerSession field.
func (r *mutationResolver) CreateViewerSession(ctx context.Context, input model.ViewerSessionInput) (*model.SessionConfig, error) {
	user, err := auth.FromContext(ctx)
	if err != nil {
		return nil, err
	}
	entry, err := r.requireLive(input.LiveID)
	if err != nil {
		return nil, err
	}
	if entry.Status != live.StatusLive {
		return nil, fmt.Errorf("live is not broadcasting")
	}
	if !entry.WatchableBy(user.ID, deref(input.Passphrase)) {
		return nil, fmt.Errorf("passphrase does not match")
	}
	if input.ClientID == "" {
		return nil, fmt.Errorf("clientId is required")
	}

	session, err := r.KVS.SessionConfig(ctx, kvs.SessionInput{
		ChannelARN: entry.ChannelARN,
		Role:       kvs.RoleViewer,
		ClientID:   input.ClientID,
	})
	if err != nil {
		slog.Error("create viewer session", "liveID", entry.ID, "clientID", input.ClientID, "error", err)
		return nil, fmt.Errorf("create KVS viewer session")
	}
	slog.Info("viewer session created",
		"event_name", "live_viewer_session_created",
		"live_id", entry.ID,
		"client_id", input.ClientID,
	)

	return toSessionConfig(entry.ID, session), nil
}

// JoinStorageSession is the resolver for the joinStorageSession field.
func (r *mutationResolver) JoinStorageSession(ctx context.Context, liveID string) (bool, error) {
	user, err := auth.FromContext(ctx)
	if err != nil {
		return false, err
	}
	entry, err := r.requireLive(liveID)
	if err != nil {
		return false, err
	}
	if entry.OwnerID != user.ID {
		return false, fmt.Errorf("only the owner can start recording")
	}
	if !entry.Record {
		return false, fmt.Errorf("recording is not enabled for this live")
	}

	slog.Info("joining storage session", "event_name", "recording_session_start_requested", "live_id", entry.ID)
	if err := r.KVS.JoinStorageSession(ctx, entry.ChannelARN); err != nil {
		slog.Error("join storage session", "liveID", entry.ID, "error", err)
		return false, fmt.Errorf("start KVS recording session")
	}
	slog.Info("storage session joined", "event_name", "recording_session_started", "live_id", entry.ID)
	return true, nil
}

// CreatePlayback is the resolver for the createPlayback field.
func (r *mutationResolver) CreatePlayback(ctx context.Context, input model.PlaybackInput) (*model.Playback, error) {
	user, err := auth.FromContext(ctx)
	if err != nil {
		return nil, err
	}
	entry, err := r.requireLive(input.LiveID)
	if err != nil {
		return nil, err
	}
	if !entry.WatchableBy(user.ID, deref(input.Passphrase)) {
		return nil, fmt.Errorf("passphrase does not match")
	}
	if !entry.HasRecording() {
		return nil, fmt.Errorf("this live has no recording")
	}

	isLive := entry.Status == live.StatusLive
	end := time.Now().UTC()
	if entry.EndedAt != nil {
		end = *entry.EndedAt
	}
	hlsURL, err := r.KVS.HLSPlaybackURL(ctx, kvs.HLSPlaybackInput{
		StreamARN: entry.StreamARN,
		Live:      isLive,
		Start:     *entry.StartedAt,
		End:       end,
	})
	if err != nil {
		slog.Error("create HLS playback URL", "liveID", entry.ID, "error", err)
		return nil, fmt.Errorf("create HLS playback URL")
	}
	slog.Info("HLS playback URL created",
		"event_name", "recording_playback_requested",
		"live_id", entry.ID,
		"playback_mode", map[bool]string{true: "live", false: "on_demand"}[isLive],
	)

	mode := model.PlaybackModeOnDemand
	if isLive {
		mode = model.PlaybackModeLive
	}
	return &model.Playback{
		LiveID:          entry.ID,
		HlsURL:          hlsURL,
		PlaybackMode:    mode,
		StartedAt:       entry.StartedAt,
		EndedAt:         entry.EndedAt,
		DurationSeconds: int(end.Sub(*entry.StartedAt).Seconds()),
	}, nil
}

// SignSignalingURL is the resolver for the signSignalingUrl field.
func (r *mutationResolver) SignSignalingURL(ctx context.Context, input model.SignSignalingURLInput) (*model.SignedURL, error) {
	user, err := auth.FromContext(ctx)
	if err != nil {
		return nil, err
	}
	entry, err := r.requireLive(input.LiveID)
	if err != nil {
		return nil, err
	}

	switch input.Role {
	case model.RoleMaster:
		if entry.OwnerID != user.ID {
			return nil, fmt.Errorf("only the owner can sign master URLs")
		}
	case model.RoleViewer:
		if !entry.WatchableBy(user.ID, deref(input.Passphrase)) {
			return nil, fmt.Errorf("passphrase does not match")
		}
	default:
		return nil, fmt.Errorf("unsupported role %q", input.Role)
	}

	if err := validateSignalingURLInput(entry, input); err != nil {
		return nil, err
	}

	signedURL, err := r.KVS.SignalingURL(ctx, kvs.SignalingURLInput{
		Endpoint:    input.Endpoint,
		QueryParams: input.QueryParams,
	})
	if err != nil {
		slog.Error("sign signaling URL", "liveID", entry.ID, "error", err)
		return nil, fmt.Errorf("sign KVS signaling URL")
	}

	return &model.SignedURL{SignedURL: signedURL}, nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.Me, error) {
	user, err := auth.FromContext(ctx)
	if err != nil {
		return nil, err
	}
	return &model.Me{UserID: user.ID, Username: user.Name}, nil
}

// Lives is the resolver for the lives field.
func (r *queryResolver) Lives(ctx context.Context, query *string) ([]*model.Live, error) {
	user, err := auth.FromContext(ctx)
	if err != nil {
		return nil, err
	}
	return r.toLives(r.LiveStore.SearchPublic(deref(query)), user.ID), nil
}

// MyLives is the resolver for the myLives field.
func (r *queryResolver) MyLives(ctx context.Context) ([]*model.Live, error) {
	user, err := auth.FromContext(ctx)
	if err != nil {
		return nil, err
	}
	return r.toLives(r.LiveStore.ListByOwner(user.ID), user.ID), nil
}

// Live is the resolver for the live field.
func (r *queryResolver) Live(ctx context.Context, id string) (*model.Live, error) {
	user, err := auth.FromContext(ctx)
	if err != nil {
		return nil, err
	}
	entry, err := r.requireLive(id)
	if err != nil {
		return nil, err
	}
	return r.toLive(entry, user.ID), nil
}

func validateSignalingURLInput(entry live.Live, input model.SignSignalingURLInput) error {
	if input.Endpoint == "" {
		return fmt.Errorf("endpoint is required")
	}
	if input.QueryParams == nil {
		return fmt.Errorf("queryParams is required")
	}
	if input.QueryParams["X-Amz-ChannelARN"] != entry.ChannelARN {
		return fmt.Errorf("queryParams X-Amz-ChannelARN does not match live")
	}
	switch input.Role {
	case model.RoleMaster:
		if deref(input.ClientID) != "" || input.QueryParams["X-Amz-ClientId"] != "" {
			return fmt.Errorf("master requests must not include clientId")
		}
	case model.RoleViewer:
		if deref(input.ClientID) == "" {
			return fmt.Errorf("clientId is required for viewer")
		}
		if input.QueryParams["X-Amz-ClientId"] != deref(input.ClientID) {
			return fmt.Errorf("queryParams X-Amz-ClientId does not match clientId")
		}
	}
	return nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type (
	mutationResolver struct{ *Resolver }
	queryResolver    struct{ *Resolver }
)
