// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"
)

type CreateLiveInput struct {
	Title      string  `json:"title"`
	Passphrase *string `json:"passphrase,omitempty"`
	Public     bool    `json:"public"`
	Record     bool    `json:"record"`
}

type EndpointSet struct {
	Wss   string `json:"wss"`
	HTTPS string `json:"https"`
}

type IceServer struct {
	Urls       []string `json:"urls"`
	Username   *string  `json:"username,omitempty"`
	Credential *string  `json:"credential,omitempty"`
	TTL        *int     `json:"ttl,omitempty"`
}

type Live struct {
	ID            string     `json:"id"`
	Title         string     `json:"title"`
	OwnerName     string     `json:"ownerName"`
	Public        bool       `json:"public"`
	Record        bool       `json:"record"`
	Status        LiveStatus `json:"status"`
	HasPassphrase bool       `json:"hasPassphrase"`
	// Whether archived media exists (or is being written) for HLS playback.
	HasRecording bool `json:"hasRecording"`
	// Whether the caller owns this live.
	Owned     bool       `json:"owned"`
	CreatedAt time.Time  `json:"createdAt"`
	StartedAt *time.Time `json:"startedAt,omitempty"`
	EndedAt   *time.Time `json:"endedAt,omitempty"`
	// Elapsed broadcast time in seconds; 0 until the broadcast starts.
	DurationSeconds int `json:"durationSeconds"`
	// Viewer app URL for this live.
	WatchURL string `json:"watchUrl"`
}

// The authenticated caller.
type Me struct {
	UserID   string `json:"userId"`
	Username string `json:"username"`
}

type Mutation struct {
}

type Playback struct {
	LiveID          string       `json:"liveId"`
	HlsURL          string       `json:"hlsUrl"`
	PlaybackMode    PlaybackMode `json:"playbackMode"`
	StartedAt       *time.Time   `json:"startedAt,omitempty"`
	EndedAt         *time.Time   `json:"endedAt,omitempty"`
	DurationSeconds int          `json:"durationSeconds"`
}

type PlaybackInput struct {
	LiveID     string  `json:"liveId"`
	Passphrase *string `json:"passphrase,omitempty"`
}

type Query struct {
}

// Everything a client needs to open a KVS WebRTC signaling connection.
type SessionConfig struct {
	LiveID     string       `json:"liveId"`
	Role       Role         `json:"role"`
	Region     string       `json:"region"`
	ChannelArn string       `json:"channelArn"`
	Endpoints  *EndpointSet `json:"endpoints"`
	IceServers []*IceServer `json:"iceServers"`
}

type SignSignalingURLInput struct {
	LiveID string `json:"liveId"`
	Role   Role   `json:"role"`
	// Required for VIEWER, forbidden for MASTER.
	ClientID   *string `json:"clientId,omitempty"`
	Passphrase *string `json:"passphrase,omitempty"`
	// KVS WSS endpoint to sign.
	Endpoint string `json:"endpoint"`
	// Query parameters produced by the KVS WebRTC SDK.
	QueryParams StringMap `json:"queryParams"`
}

type SignedURL struct {
	SignedURL string `json:"signedUrl"`
}

type ViewerSessionInput struct {
	LiveID     string  `json:"liveId"`
	ClientID   string  `json:"clientId"`
	Passphrase *string `json:"passphrase,omitempty"`
}

type LiveStatus string

const (
	LiveStatusCreated LiveStatus = "CREATED"
	LiveStatusLive    LiveStatus = "LIVE"
	LiveStatusEnded   LiveStatus = "ENDED"
)

var AllLiveStatus = []LiveStatus{
	LiveStatusCreated,
	LiveStatusLive,
	LiveStatusEnded,
}

func (e LiveStatus) IsValid() bool {
	switch e {
	case LiveStatusCreated, LiveStatusLive, LiveStatusEnded:
		return true
	}
	return false
}

func (e LiveStatus) String() string {
	return string(e)
}

func (e *LiveStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = LiveStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid LiveStatus", str)
	}
	return nil
}

func (e LiveStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *LiveStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e LiveStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type PlaybackMode string

const (
	PlaybackModeLive     PlaybackMode = "LIVE"
	PlaybackModeOnDemand PlaybackMode = "ON_DEMAND"
)

var AllPlaybackMode = []PlaybackMode{
	PlaybackModeLive,
	PlaybackModeOnDemand,
}

func (e PlaybackMode) IsValid() bool {
	switch e {
	case PlaybackModeLive, PlaybackModeOnDemand:
		return true
	}
	return false
}

func (e PlaybackMode) String() string {
	return string(e)
}

func (e *PlaybackMode) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = PlaybackMode(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid PlaybackMode", str)
	}
	return nil
}

func (e PlaybackMode) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *PlaybackMode) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e PlaybackMode) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type Role string

const (
	RoleMaster Role = "MASTER"
	RoleViewer Role = "VIEWER"
)

var AllRole = []Role{
	RoleMaster,
	RoleViewer,
}

func (e Role) IsValid() bool {
	switch e {
	case RoleMaster, RoleViewer:
		return true
	}
	return false
}

func (e Role) String() string {
	return string(e)
}

func (e *Role) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Role(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Role", str)
	}
	return nil
}

func (e Role) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *Role) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e Role) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
